### ISSUE TITLE
Demo Design already buggy

### ISSUE THREAD

**Issue by sircode** [lukasboc/onepagercms#137]
![OP_bug2](https://github.com/lukasboc/onepagercms/assets/555703/c9a3e90d-6f75-42fb-b3d8-28f07b590d78)
![OP_bugs](https://github.com/lukasboc/onepagercms/assets/555703/f74d7a8a-669c-42df-8c53-181020a1cbda)
**Describe the bug**

Basic design is already buggy. See pics.
Possibly CSS problems.

Tested with Chrome/Win10

**Comment by lukasboc** [comment]
Image 1: what you are looking at is the preview. Since it’s inside a frame and the backend navigation is fixed it’s intended behavior.

Image 2: the background color of the navigation is slightly transparent. It’s intended to see elements through the background.

No problems here.
